version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - scam_sms_service
      - mongo
    env_file:
      - ./backend/.env
    environment:
      - MONGO_URI=mongodb://mongo:27017/expense_db
    networks:
      - scam_net

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - scam_net
    environment:
    - CHOKIDAR_USEPOLLING=true

  scam_sms_service:
    build: ./services/scam_detector
    ports:
      - "8000:8000"
    networks:
      - scam_net
    
  whisper_stt_service:
    build: ./services/whisper_stt
    ports:
      - "8001:8001"
    env_file:
      - ./services/whisper_stt/.env
    networks:
      - scam_net
  
  tts_service:
    build: ./services/tts_service
    ports:
      - "8002:8002"
    networks:
      - scam_net
    
  parse_text_service:
    build: ./services/parse_text
    ports:
      - "8003:8003"
    env_file:
      - ./services/parse_text/.env
    networks:
      - scam_net
    
  ocr_explain_service:
    build: ./services/ocr_explain
    ports:
      - "8004:8004"
    env_file:
      - ./services/ocr_explain/.env
    networks:
      - scam_net


  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - scam_net


networks:
  scam_net:

volumes:
  mongo_data: